-------------------
--Gamma Adjust
-------------------

local gammaAdjustScene = ZO_Scene:New("gammaAdjust", SCENE_MANAGER)
gammaAdjustScene:AddFragment(GAMMA_SCENE_FRAGMENT)

-------------------
--Crown Store Scene
-------------------

local marketScene = ZO_RemoteScene:New("market", SCENE_MANAGER)
marketScene:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW_NO_KEYBIND_STRIP)
marketScene:AddFragmentGroup(FRAGMENT_GROUP.PLAYER_PROGRESS_BAR_KEYBOARD_CURRENT)
marketScene:AddFragment(MARKET_KEYBIND_STRIP_MUNGE_BACKDROP_FRAGMENT)
marketScene:AddFragment(FRAME_TARGET_STANDARD_RIGHT_PANEL_FRAGMENT)
marketScene:AddFragment(FRAME_PLAYER_FRAGMENT)
marketScene:AddFragment(FRAME_EMOTE_FRAGMENT_INVENTORY)
marketScene:AddFragment(STOP_MOVEMENT_FRAGMENT)
marketScene:AddFragment(ITEM_PREVIEW_FRAGMENT)
marketScene:AddFragment(MARKET_WINDOW_SOUNDS)
marketScene:AddFragment(MARKET_PREVIEW_KEYBIND_INTERCEPT_LAYER_FRAGMENT)

-------------------
--Crown Store Announcement Scene
-------------------

local announcementScene = ZO_RemoteScene:New("marketAnnouncement", SCENE_MANAGER)
announcementScene:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW_NO_KEYBIND_STRIP)

-------------------
--Inventory Scene
-------------------

local inventoryScene = SCENE_MANAGER:GetScene("inventory")
inventoryScene:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
inventoryScene:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_CENTERED)
inventoryScene:AddFragmentGroup(FRAGMENT_GROUP.PLAYER_PROGRESS_BAR_KEYBOARD_CURRENT)
inventoryScene:AddFragment(RIGHT_PANEL_BG_FRAGMENT)
inventoryScene:AddFragment(WIDE_LEFT_PANEL_BG_FRAGMENT)
inventoryScene:AddFragment(CHARACTER_WINDOW_FRAGMENT)
inventoryScene:AddFragment(CHARACTER_WINDOW_STATS_FRAGMENT)
inventoryScene:AddFragment(INVENTORY_MENU_FRAGMENT)
inventoryScene:AddFragment(FRAME_EMOTE_FRAGMENT_INVENTORY)
inventoryScene:AddFragment(INVENTORY_WINDOW_SOUNDS)

-------------------
--Bank Scene
-------------------

local bankScene = SCENE_MANAGER:GetScene("bank")
bankScene:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
bankScene:AddFragment(RIGHT_PANEL_BG_FRAGMENT)
bankScene:AddFragment(BANK_MENU_FRAGMENT)
bankScene:AddFragment(BANK_WINDOW_SOUNDS)
bankScene:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
bankScene:AddFragment(ZO_TutorialTriggerFragment:New(TUTORIAL_TRIGGER_ACCOUNT_BANK_OPENED))

-------------------
--Guild Bank Scene
-------------------

local guildBankScene = SCENE_MANAGER:GetScene("guildBank")
guildBankScene:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
guildBankScene:AddFragment(RIGHT_PANEL_BG_FRAGMENT)
guildBankScene:AddFragment(GUILD_BANK_MENU_FRAGMENT)
guildBankScene:AddFragment(BANK_WINDOW_SOUNDS)
guildBankScene:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
guildBankScene:AddFragment(ZO_TutorialTriggerFragment:New(TUTORIAL_TRIGGER_GUILD_BANK_OPENED))

----------------
--Lockpick Scene
----------------

LOCK_PICK_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
LOCK_PICK_SCENE:AddFragment(LOCKPICK_FRAGMENT)
LOCK_PICK_SCENE:AddFragment(UNIFORM_BLUR_FRAGMENT)
LOCK_PICK_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
LOCK_PICK_SCENE:AddFragment(LOCKPICK_TUTORIAL_FRAGMENT)

----------------
--Combat Skills Scene
----------------

local skillsScene = ZO_Scene:New("skills", SCENE_MANAGER)
skillsScene:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
skillsScene:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_STANDARD_RIGHT_PANEL)
skillsScene:AddFragmentGroup(FRAGMENT_GROUP.PLAYER_PROGRESS_BAR_KEYBOARD_CURRENT)
skillsScene:AddFragment(RIGHT_BG_FRAGMENT)
skillsScene:AddFragment(TREE_UNDERLAY_FRAGMENT)
skillsScene:AddFragment(TITLE_FRAGMENT)
skillsScene:AddFragment(SKILLS_FRAGMENT)
skillsScene:AddFragment(SKILLS_ACTION_BAR_FRAGMENT)
skillsScene:AddFragment(FRAME_EMOTE_FRAGMENT_SKILLS)
skillsScene:AddFragment(SKILLS_TITLE_FRAGMENT)
skillsScene:AddFragment(SKILLS_WINDOW_SOUNDS)
skillsScene:AddFragment(ZO_TutorialTriggerFragment:New(TUTORIAL_TRIGGER_COMBAT_SKILLS_OPENED))

------------------------
--Lore Reader (From Inventory)
------------------------

LORE_READER_INVENTORY_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
LORE_READER_INVENTORY_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_CENTERED_UNIFORM_BLUR)
LORE_READER_INVENTORY_SCENE:AddFragment(LORE_READER_FRAGMENT)
LORE_READER_INVENTORY_SCENE:AddFragment(FRAME_EMOTE_FRAGMENT_INVENTORY)
LORE_READER_INVENTORY_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)

------------------------
--Lore Reader (From Lore Library)
------------------------

LORE_READER_LORE_LIBRARY_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
LORE_READER_LORE_LIBRARY_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_STANDARD_RIGHT_PANEL)
LORE_READER_LORE_LIBRARY_SCENE:AddFragment(LORE_READER_FRAGMENT)
LORE_READER_LORE_LIBRARY_SCENE:AddFragment(FRAME_EMOTE_FRAGMENT_JOURNAL)
LORE_READER_LORE_LIBRARY_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)

------------------------
--Lore Reader (From Interaction)
------------------------

LORE_READER_INTERACTION_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
LORE_READER_INTERACTION_SCENE:AddFragment(LORE_READER_FRAGMENT)
LORE_READER_INTERACTION_SCENE:AddFragment(UNIFORM_BLUR_FRAGMENT)
LORE_READER_INTERACTION_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)

------------------------
--Treasure Map (From Inventory)
------------------------

TREASURE_MAP_INVENTORY_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
TREASURE_MAP_INVENTORY_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_CENTERED_UNIFORM_BLUR)
TREASURE_MAP_INVENTORY_SCENE:AddFragment(TREASURE_MAP_FRAGMENT)
TREASURE_MAP_INVENTORY_SCENE:AddFragment(TREASURE_MAP_SOUNDS)
TREASURE_MAP_INVENTORY_SCENE:AddFragment(FRAME_EMOTE_FRAGMENT_INVENTORY)
TREASURE_MAP_INVENTORY_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)

------------------------
--Treasure Map (From Quick Slot)
------------------------

TREASURE_MAP_QUICK_SLOT_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
TREASURE_MAP_QUICK_SLOT_SCENE:AddFragment(TREASURE_MAP_FRAGMENT)
TREASURE_MAP_QUICK_SLOT_SCENE:AddFragment(TREASURE_MAP_SOUNDS)
TREASURE_MAP_QUICK_SLOT_SCENE:AddFragment(UNIFORM_BLUR_FRAGMENT)
TREASURE_MAP_QUICK_SLOT_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)

-----------------------
--Game Menu
-----------------------

GAME_MENU_SCENE:AddFragment(MOUSE_UI_MODE_FRAGMENT)
GAME_MENU_SCENE:AddFragment(UI_SHORTCUTS_ACTION_LAYER_FRAGMENT)
GAME_MENU_SCENE:AddFragment(CLEAR_CURSOR_FRAGMENT)
GAME_MENU_SCENE:AddFragment(UI_COMBAT_OVERLAY_FRAGMENT)
GAME_MENU_SCENE:AddFragment(FRAME_PLAYER_FRAGMENT)
GAME_MENU_SCENE:AddFragment(SYSTEM_WINDOW_SOUNDS)
GAME_MENU_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
GAME_MENU_SCENE:AddFragment(PERFORMANCE_METER_FRAGMENT)

-------------------
--Stats Scene
-------------------

STATS_SCENE = ZO_Scene:New("stats", SCENE_MANAGER)
STATS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.MOUSE_DRIVEN_UI_WINDOW)
STATS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_CENTERED)
STATS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.PLAYER_PROGRESS_BAR_KEYBOARD_CURRENT)
STATS_SCENE:AddFragment(STATS_BG_FRAGMENT)
STATS_SCENE:AddFragment(STATS_FRAGMENT)
STATS_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
STATS_SCENE:AddFragment(FRAME_EMOTE_FRAGMENT_SKILLS)
STATS_SCENE:AddFragment(CHARACTER_WINDOW_SOUNDS)

-----------------------
--Siege Bar Scene
-----------------------

SIEGE_BAR_SCENE:AddFragment(SIEGE_ACTION_LAYER_FRAGMENT)
SIEGE_BAR_SCENE:AddFragment(SIEGE_HUD_FRAGMENT)
SIEGE_BAR_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
SIEGE_BAR_SCENE:AddFragment(UNIT_FRAMES_FRAGMENT)
SIEGE_BAR_SCENE:AddFragment(PLAYER_ATTRIBUTE_BARS_FRAGMENT)
SIEGE_BAR_SCENE:AddFragment(COMPASS_FRAME_FRAGMENT)

SIEGE_BAR_UI_SCENE:AddFragment(SIEGE_HUD_FRAGMENT)
SIEGE_BAR_UI_SCENE:AddFragment(SIEGE_ACTION_LAYER_FRAGMENT)
SIEGE_BAR_UI_SCENE:AddFragment(PLAYER_PROGRESS_BAR_FRAGMENT)
SIEGE_BAR_UI_SCENE:AddFragment(UNIT_FRAMES_FRAGMENT)
SIEGE_BAR_UI_SCENE:AddFragment(PLAYER_ATTRIBUTE_BARS_FRAGMENT)
SIEGE_BAR_UI_SCENE:AddFragment(COMPASS_FRAME_FRAGMENT)

---------------------------
--Champion Perks Scene
---------------------------

CHAMPION_PERKS_SCENE:AddFragment(CHAMPION_PERKS_CONSTELLATIONS_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(CHAMPION_KEYBIND_STRIP_FADE_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(KEYBIND_STRIP_MUNGE_BACKDROP_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(MOUSE_UI_MODE_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(UI_SHORTCUTS_ACTION_LAYER_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(CLEAR_CURSOR_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(UI_COMBAT_OVERLAY_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(END_IN_WORLD_INTERACTIONS_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(MINIMIZE_CHAT_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(CHAMPION_PERKS_CHOSEN_ATTRIBUTE_TYPE_POINT_COUNTER_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(CHAMPION_PERKS_CHOSEN_ATTRIBUTE_TYPE_EARNED_POINT_COUNTER_FRAGMENT)
CHAMPION_PERKS_SCENE:AddFragment(CHAMPION_WINDOW_SOUNDS)
CHAMPION_PERKS_SCENE:AddFragment(FRAME_EMOTE_FRAGMENT_CHAMPION)
CHAMPION_PERKS_SCENE:AddFragment(FRAME_PLAYER_FRAGMENT)
