FRAGMENT_GROUP =
{
    MOUSE_DRIVEN_UI_WINDOW =
    {
        MOUSE_UI_MODE_FRAGMENT,
        KEYBIND_STRIP_FADE_FRAGMENT,
        KEYBIND_STRIP_MUNGE_BACKDROP_FRAGMENT,
        UI_SHORTCUTS_ACTION_LAYER_FRAGMENT,
        CLEAR_CURSOR_FRAGMENT,
        UI_COMBAT_OVERLAY_FRAGMENT,
        END_IN_WORLD_INTERACTIONS_FRAGMENT,
    },

    MOUSE_DRIVEN_UI_WINDOW_NO_COMBAT_OVERLAY =
    {
        MOUSE_UI_MODE_FRAGMENT,
        KEYBIND_STRIP_FADE_FRAGMENT,
        UI_SHORTCUTS_ACTION_LAYER_FRAGMENT,
        CLEAR_CURSOR_FRAGMENT,
        END_IN_WORLD_INTERACTIONS_FRAGMENT,
    },

    MOUSE_DRIVEN_UI_WINDOW_NO_KEYBIND_STRIP =
    {
        MOUSE_UI_MODE_FRAGMENT,
        UI_SHORTCUTS_ACTION_LAYER_FRAGMENT,
        CLEAR_CURSOR_FRAGMENT,
        UI_COMBAT_OVERLAY_FRAGMENT,
        END_IN_WORLD_INTERACTIONS_FRAGMENT,
    },

    GAMEPAD_DRIVEN_UI_WINDOW =
    {
        MOUSE_UI_MODE_FRAGMENT, --still need this as it blocks clicks from becoming attacks
        GAMEPAD_UI_MODE_FRAGMENT,
        GAMEPAD_ACTION_LAYER_FRAGMENT,
        KEYBIND_STRIP_GAMEPAD_FRAGMENT,
        KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT,
        UI_SHORTCUTS_ACTION_LAYER_FRAGMENT,
        CLEAR_CURSOR_FRAGMENT,
        UI_COMBAT_OVERLAY_FRAGMENT,
        END_IN_WORLD_INTERACTIONS_FRAGMENT,
        HIDE_MOUSE_FRAGMENT,
    },

    GAMEPAD_DRIVEN_UI_NO_KEYBIND_BACKGROUND_WINDOW =
    {
        MOUSE_UI_MODE_FRAGMENT, --still need this as it blocks clicks from becoming attacks
        GAMEPAD_UI_MODE_FRAGMENT,
        GAMEPAD_ACTION_LAYER_FRAGMENT,
        KEYBIND_STRIP_GAMEPAD_FRAGMENT,
        UI_SHORTCUTS_ACTION_LAYER_FRAGMENT,
        CLEAR_CURSOR_FRAGMENT,
        UI_COMBAT_OVERLAY_FRAGMENT,
        END_IN_WORLD_INTERACTIONS_FRAGMENT,
        HIDE_MOUSE_FRAGMENT,
    },

    FRAME_TARGET_CENTERED =
    {
        FRAME_TARGET_CENTERED_FRAGMENT,
        FRAME_TARGET_BLUR_CENTERED_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
    },

    FRAME_TARGET_STANDARD_RIGHT_PANEL =
    {
        FRAME_TARGET_STANDARD_RIGHT_PANEL_FRAGMENT,
        FRAME_TARGET_BLUR_STANDARD_RIGHT_PANEL_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
    },

    FRAME_TARGET_CENTERED_UNIFORM_BLUR =
    {
        FRAME_TARGET_CENTERED_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
        UNIFORM_BLUR_FRAGMENT,
    },

    FRAME_TARGET_GAMEPAD =
    {
        FRAME_TARGET_GAMEPAD_FRAGMENT,
        FRAME_TARGET_BLUR_GAMEPAD_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
    },

    FRAME_TARGET_GAMEPAD_OPTIONS =
    {
        FRAME_TARGET_GAMEPAD_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
    },

    FRAME_TARGET_GAMEPAD_LEFT =
    {
        FRAME_TARGET_LEFT_GAMEPAD_FRAGMENT,
        FRAME_TARGET_LEFT_BLUR_GAMEPAD_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
    },

    FRAME_TARGET_CRAFTING_GAMEPAD =
    {
        FRAME_TARGET_GAMEPAD_FRAGMENT,
        FRAME_TARGET_BLUR_GAMEPAD_FRAGMENT,
    },

    READ_ONLY_EQUIPPED_ITEMS =
    {
        THIN_LEFT_PANEL_BG_FRAGMENT,
        READ_ONLY_CHARACTER_WINDOW_FRAGMENT,
    },

    PLAYER_PROGRESS_BAR_KEYBOARD = 
    {
        PLAYER_PROGRESS_BAR_FRAGMENT,
        PLAYER_PROGRESS_BAR_KEYBOARD_TEXTURE_SWAP_FRAGMENT,
    },

    PLAYER_PROGRESS_BAR_KEYBOARD_CURRENT = 
    {
        PLAYER_PROGRESS_BAR_FRAGMENT,
        PLAYER_PROGRESS_BAR_CURRENT_FRAGMENT,
        PLAYER_PROGRESS_BAR_KEYBOARD_TEXTURE_SWAP_FRAGMENT,
    },

    PLAYER_PROGRESS_BAR_GAMEPAD = 
    {
        PLAYER_PROGRESS_BAR_FRAGMENT,
        PLAYER_PROGRESS_BAR_GAMEPAD_NAME_LOCATION_ANCHOR_FRAGMENT,
        PLAYER_PROGRESS_BAR_GAMEPAD_TEXTURE_SWAP_FRAGMENT,
    },

    PLAYER_PROGRESS_BAR_GAMEPAD_CURRENT = 
    {
        PLAYER_PROGRESS_BAR_FRAGMENT,
        PLAYER_PROGRESS_BAR_CURRENT_FRAGMENT,
        PLAYER_PROGRESS_BAR_GAMEPAD_NAME_LOCATION_ANCHOR_FRAGMENT,
        PLAYER_PROGRESS_BAR_GAMEPAD_TEXTURE_SWAP_FRAGMENT,
    },

    FRAME_TARGET_GAMEPAD_RIGHT =
    {
        FRAME_TARGET_GAMEPAD_RIGHT_FRAGMENT,
        FRAME_TARGET_BLUR_GAMEPAD_RIGHT_FRAGMENT,
        FRAME_PLAYER_FRAGMENT,
    },
}

ZO_GAMEPAD_DIALOG_FRAGMENT_GROUP = FRAGMENT_GROUP.GAMEPAD_DRIVEN_UI_WINDOW
