KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_VIDEO, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_VIDEO))
KEYBOARD_OPTIONS:AddUserPanel(SETTING_PANEL_AUDIO, GetString("SI_SETTINGSYSTEMPANEL", SETTING_PANEL_AUDIO))
