ZO_RESTYLE_SHEETS_KEYBOARD_FRAGMENT_GROUP = 
{
    RESTYLE_PREVIEW_OPTIONS_FRAGMENT,
    ITEM_PREVIEW_KEYBOARD:GetFragment(),
    MEDIUM_LEFT_PANEL_BG_FRAGMENT,
    ZO_RESTYLE_SHEET_WINDOW_FRAGMENT,
    MINIMIZE_CHAT_FRAGMENT,
}

HELP_TUTORIALS_KEYBOARD_FRAGMENT_GROUP_BASE =
{
    HELP_TUTORIALS_FRAGMENT,
    RIGHT_BG_FRAGMENT,
    TITLE_FRAGMENT,
    TREE_UNDERLAY_FRAGMENT,
    HELP_WINDOW_SOUNDS,
}

HELP_TUTORIALS_OVERLAY_KEYBOARD_FRAGMENT_GROUP = ZO_ShallowTableCopy(HELP_TUTORIALS_KEYBOARD_FRAGMENT_GROUP_BASE)
table.insert(HELP_TUTORIALS_OVERLAY_KEYBOARD_FRAGMENT_GROUP, ZO_SetTitleFragment:New(SI_HELP_TUTORIALS))