--------------------------------
--Gamepad Voice Chat Scenes
--------------------------------
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.GAMEPAD_DRIVEN_UI_WINDOW)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_GAMEPAD_RIGHT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(MINIMIZE_CHAT_FRAGMENT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(GAMEPAD_MENU_SOUND_FRAGMENT)
GAMEPAD_VOICECHAT_CHANNELS_SCENE:AddFragment(GAMEPAD_VOICECHAT_CHANNELS_FRAGMENT)

GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.GAMEPAD_DRIVEN_UI_WINDOW)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragmentGroup(FRAGMENT_GROUP.FRAME_TARGET_GAMEPAD_RIGHT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(MINIMIZE_CHAT_FRAGMENT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(GAMEPAD_MENU_SOUND_FRAGMENT)
GAMEPAD_VOICECHAT_PARTICIPANTS_SCENE:AddFragment(GAMEPAD_VOICECHAT_PARTICIPANTS_FRAGMENT)
