ZO_QUEST_ASSISTANCE_CATEGORIES_DATA =
{
    categoryEnumStringPrefix = "SI_CUSTOMERSERVICEQUESTASSISTANCECATEGORIES",
    categoryEnumMin = CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_MIN_VALUE,
    categoryEnumMax = CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_MAX_VALUE,
    invalidCategory = CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NONE,
    ticketCategoryMap =
    {
        [CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NPC_MOBS] =
        {
            ticketCategory = TICKET_CATEGORY_QUEST_NPC_MOBS,
        },
        [CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_ITEM_MISSING] =
        {
            ticketCategory = TICKET_CATEGORY_QUEST_ITEM_MISSING,
        },
    }
}

ZO_ITEM_ASSISTANCE_CATEGORIES_DATA =
{
    categoryEnumStringPrefix = "SI_CUSTOMERSERVICEITEMASSISTANCECATEGORIES",
    categoryEnumMin = CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MIN_VALUE,
    categoryEnumMax = CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MAX_VALUE,
    invalidCategory = CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_NONE,
    ticketCategoryMap =
    {
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_NOT_WORKING] =
        {
            ticketCategory = TICKET_CATEGORY_ITEM_NOT_WORKING,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MISSING_CROWNS] =
        {
            ticketCategory = TICKET_CATEGORY_ITEM_MISSING_CROWNS,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_FROM_CROWN_STORE] =
        {
            ticketCategory = TICKET_CATEGORY_ITEM_FROM_CROWN_STORE,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_LOST] =
        {
            ticketCategory = TICKET_CATEGORY_ITEM_LOST,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_CANT_ACQUIRE] =
        {
            ticketCategory = TICKET_CATEGORY_ITEM_CANT_ACQUIRE,
        },
    }
}