ZO_HELP_TICKET_FIELD_TYPE =
{
    IMPACT =  1,
    CATEGORY = 2,
    SUBCATEGORY = 3,
    DETAILS = 4,
    DESCRIPTION = 5,
    ATTACH_SCREENSHOT = 6,
    SUBMIT = 7,
}

ZO_HELP_SUBMIT_FEEDBACK_FIELD_DATA =
{
    [ZO_HELP_TICKET_FIELD_TYPE.IMPACT] =
    {
        enumStringPrefix = "SI_CUSTOMERSERVICESUBMITFEEDBACKIMPACTS",
        minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_MIN_VALUE,
        maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_MAX_VALUE,
        invalidEntry = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_IMPACT_NONE,
    },
    [ZO_HELP_TICKET_FIELD_TYPE.CATEGORY] =
    {
        enumStringPrefix = "SI_CUSTOMERSERVICESUBMITFEEDBACKCATEGORIES",
        minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_MIN_VALUE,
        maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_MAX_VALUE,
        invalidEntry = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_NONE,
    },
    [ZO_HELP_TICKET_FIELD_TYPE.SUBCATEGORY] =
    {
        enumStringPrefix = "SI_CUSTOMERSERVICESUBMITFEEDBACKSUBCATEGORIES",
        universallyAddEnum = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_NONE,
        categoryContextualData = 
        {
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_ALLIANCE_WAR] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_GRAVEYARD,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ALLIANCE_WAR_SIEGE,
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_AUDIO] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_MUSIC,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_AUDIO_OTHER,
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_CHARACTERS] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CHARACTERS_ABILITIES,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_CHARACTERS_TARGETING,
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_COMBAT] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_ABILITY,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_COMBAT_NPC,
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_ITEMS] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_ARMOR,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_ITEMS_WEAPONS,
                detailsTitle = GetString(SI_CUSTOMER_SERVICE_ITEM_NAME),
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_GAME_SYSTEM] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GAME_SYSTEM_CHAT,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GAME_SYSTEM_VENDOR,
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_GRAPHICS] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_ART_ANIMATION,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_GRAPHICS_WEATHER,
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_QUESTS] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_DIALOG_VOICEOVER,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_QUESTS_REWARDS,
                detailsTitle = GetString(SI_CUSTOMER_SERVICE_QUEST_NAME),
            },
            [CUSTOMER_SERVICE_SUBMIT_FEEDBACK_CATEGORY_TEXT] =
            {
                minValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_DIALOG_VOICEOVER,
                maxValue = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_TEXT_BOOKS,
            },
        },
        invalidEntry = CUSTOMER_SERVICE_SUBMIT_FEEDBACK_SUBCATEGORY_NONE,
    },
}