ZO_QUEST_ASSISTANCE_CATEGORIES_DATA =
{
    categoryEnumStringPrefix = "SI_CUSTOMERSERVICEQUESTASSISTANCECATEGORIES",
    categoryEnumOrderedValues = 
    {
        CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NONE,
        CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NPC_MOBS,
        CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_ITEM_MISSING,
    },
    invalidCategory = CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NONE,
    ticketCategoryMap =
    {
        [CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_NPC_MOBS] =
        {
            ticketCategory = 763,
        },
        [CUSTOMER_SERVICE_QUEST_ASSISTANCE_CATEGORY_ITEM_MISSING] =
        {
            ticketCategory = 983,
        },
    }
}

ZO_ITEM_ASSISTANCE_CATEGORIES_DATA =
{
    categoryEnumStringPrefix = "SI_CUSTOMERSERVICEITEMASSISTANCECATEGORIES",
    categoryEnumOrderedValues =
    {
        CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_NONE,
        CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MISSING_CROWNS,
        CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_FROM_CROWN_STORE,
        CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_LOST,
        CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_CANT_ACQUIRE,
    },
    invalidCategory = CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_NONE,
    ticketCategoryMap =
    {
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_MISSING_CROWNS] =
        {
            ticketCategory = 981,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_FROM_CROWN_STORE] =
        {
            ticketCategory = 982,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_LOST] =
        {
            ticketCategory = 897,
        },
        [CUSTOMER_SERVICE_ITEM_ASSISTANCE_CATEGORY_CANT_ACQUIRE] =
        {
            ticketCategory = 979,
        },
    }
}