ZO_MIN_CANVAS_WIDTH = GetMinUICanvasWidth()
ZO_MIN_CANVAS_HEIGHT = GetMinUICanvasHeight()

ZO_COMMON_INFO_DEFAULT_KEYBOARD_BOTTOM_OFFSET_Y = -210
ZO_COMMON_INFO_DEFAULT_GAMEPAD_BOTTOM_OFFSET_Y = -235

--Ordering for top level windows that are at high tier.
ZO_HIGH_TIER_UI_ERRORS = 10
ZO_HIGH_TIER_TRIAL_DIALOG = 10
ZO_HIGH_TIER_CENTER_SCREEN_ANNOUNCE = 20
ZO_HIGH_TIER_UNDER_GAMEPAD_KEYBIND_STRIP_BG = 90
ZO_HIGH_TIER_GAMEPAD_KEYBIND_STRIP_BG = 100
ZO_HIGH_TIER_GAMEPAD_KEYBIND_STRIP = 110
ZO_HIGH_TIER_SCREEN_ADJUST = 115
ZO_HIGH_TIER_OVER_GAMEPAD_KEYBIND_STRIP = 120
ZO_HIGH_TIER_DOWNLOAD_BAR = 120
ZO_HIGH_TIER_VOICE_CHAT_HUD = 130
ZO_HIGH_TIER_TOOLTIPS = 140
ZO_HIGH_TIER_GAMEPAD_COMBO_BOX_DROPDOWN = 140
ZO_HIGH_TIER_CUTSCENE_UNDERLAY = 141
ZO_HIGH_TIER_GAMEPAD_AUTO_SAVING_ICON = 142
ZO_HIGH_TIER_ALERT_TEXT = 145
ZO_HIGH_TIER_GAMEPAD_DISCONNECT_POPUP = 145
ZO_HIGH_TIER_ANCHOR_EDITOR_HIGHLIGHT = 150
