local ZO_KEYBOARD_CURRENCY_OPTIONS_BASE =
{
    showTooltips = true,
    font = "ZoFontGameLargeBold",
    iconSide = RIGHT,
}

ZO_KEYBOARD_CARRIED_CURRENCY_OPTIONS =  ZO_ShallowTableCopy(ZO_KEYBOARD_CURRENCY_OPTIONS_BASE)
ZO_KEYBOARD_CARRIED_CURRENCY_OPTIONS.customTooltip = SI_CURRENCY_YOUR_GOLD

ZO_KEYBOARD_BANKED_CURRENCY_OPTIONS = ZO_ShallowTableCopy(ZO_KEYBOARD_CURRENCY_OPTIONS_BASE)
ZO_KEYBOARD_BANKED_CURRENCY_OPTIONS.customTooltip = SI_CURRENCY_YOUR_BANKED_GOLD

ZO_KEYBOARD_CARRIED_TELVAR_OPTIONS = ZO_ShallowTableCopy(ZO_KEYBOARD_CURRENCY_OPTIONS_BASE)
ZO_KEYBOARD_CARRIED_TELVAR_OPTIONS.customTooltip = SI_CURRENCY_YOUR_TELVAR_STONES

ZO_KEYBOARD_BANKED_TELVAR_OPTIONS = ZO_ShallowTableCopy(ZO_KEYBOARD_CURRENCY_OPTIONS_BASE)
ZO_KEYBOARD_BANKED_TELVAR_OPTIONS.customTooltip = SI_CURRENCY_YOUR_BANKED_TELVAR_STONES

ZO_KEYBOARD_CARRIED_WRIT_VOUCHER_OPTIONS = ZO_ShallowTableCopy(ZO_KEYBOARD_CURRENCY_OPTIONS_BASE)
ZO_KEYBOARD_CARRIED_WRIT_VOUCHER_OPTIONS.customTooltip = SI_CURRENCY_WRIT_VOUCHERS

ZO_ALTERNATE_CURRENCY_OPTIONS = ZO_ShallowTableCopy(ZO_KEYBOARD_CURRENCY_OPTIONS_BASE)