-- TODO: rename gamepad scenes into console scenes

-----------------------
--Create Link Account
-----------------------
CREATE_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
CREATE_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT)
CREATE_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_FRAGMENT)
CREATE_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(PREGAME_ANIMATED_BACKGROUND_FRAGMENT)

-----------------------
--Create Account
-----------------------
CREATE_ACCOUNT_GAMEPAD_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
CREATE_ACCOUNT_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT)
CREATE_ACCOUNT_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_FRAGMENT)
CREATE_ACCOUNT_GAMEPAD_SCENE:AddFragment(PREGAME_ANIMATED_BACKGROUND_FRAGMENT)
CREATE_ACCOUNT_GAMEPAD_SCENE:AddFragment(CREATE_ACCOUNT_IMAGES_FRAGMENT_CONSOLE)

-----------------------
--Create Account Final
-----------------------
CREATE_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
CREATE_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT)
CREATE_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_FRAGMENT)
CREATE_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(PREGAME_ANIMATED_BACKGROUND_FRAGMENT)
CREATE_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(CREATE_ACCOUNT_IMAGES_FRAGMENT_CONSOLE)

-----------------------
--Link Account
-----------------------
LINK_ACCOUNT_GAMEPAD_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
LINK_ACCOUNT_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT)
LINK_ACCOUNT_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_FRAGMENT)
LINK_ACCOUNT_GAMEPAD_SCENE:AddFragment(PREGAME_ANIMATED_BACKGROUND_FRAGMENT)
LINK_ACCOUNT_GAMEPAD_SCENE:AddFragment(LINK_ACCOUNT_IMAGES_FRAGMENT_CONSOLE)

-----------------------
--Link Account Final
-----------------------
LINK_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
LINK_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT)
LINK_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_FRAGMENT)
LINK_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(PREGAME_ANIMATED_BACKGROUND_FRAGMENT)
LINK_ACCOUNT_FINAL_GAMEPAD_SCENE:AddFragment(LINK_ACCOUNT_IMAGES_FRAGMENT_CONSOLE)

-----------------------
--Confirm Link Account
-----------------------
CONFIRM_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(GAMEPAD_NAV_QUADRANT_1_BACKGROUND_FRAGMENT)
CONFIRM_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_BACKDROP_FRAGMENT)
CONFIRM_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(KEYBIND_STRIP_GAMEPAD_FRAGMENT)
CONFIRM_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(PREGAME_ANIMATED_BACKGROUND_FRAGMENT)
CONFIRM_LINK_ACCOUNT_SCREEN_GAMEPAD_SCENE:AddFragment(LINK_ACCOUNT_IMAGES_FRAGMENT_CONSOLE)

