CREATE_ACCOUNT_IMAGES_FRAGMENT_CONSOLE = ZO_FadeSceneFragment:New(ZO_SideImages_CreateAccount_Console)
LINK_ACCOUNT_IMAGES_FRAGMENT_CONSOLE = ZO_FadeSceneFragment:New(ZO_SideImages_LinkAccount_Console)
